<a href="https://colab.research.google.com/github/guillermohenrion/Intro-Python/blob/master/Encoders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.preprocessing import LabelBinarizer, LabelEncoder, OneHotEncoder
import numpy as np

In [16]:
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(data)

print(integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(np.reshape(data, (len(data),1)).tolist())

print(onehot_encoded)


X = [["US", "M"], ["UK", "M"], ["FR", "F"]]
OneHotEncoder().fit_transform(X).toarray()

[0 0 2 0 1 1 2 0 2 1]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


array([[0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

In [110]:
from sklearn import preprocessing

label_encoder = LabelEncoder()
values=['red', 'blue', 'green', 'green', 'yellow', 'yellow', 'yellow']
integer_encoded = label_encoder.fit_transform(values)
label_encoder.classes_

lbb = preprocessing.LabelBinarizer()
lbb.fit(integer_encoded)

lbb.classes_
lbb.transform([0, 0, 1,2,3, 3])

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1]])

[Encodings](https://towardsdatascience.com/all-about-categorical-variable-encoding-305f3361fd02)

[Categorical vs Continuous variables](https://medium.com/@outside2SDs/an-overview-of-correlation-measures-between-categorical-and-continuous-variables-4c7f85610365)

